apiVersion: v1
kind: Service
metadata:
  name: portfolio-clusterip
  namespace: portfolio
  labels:
    app: portfolio
spec:
  type: ClusterIP   # default, you can even omit this line
  selector:
    app: portfolio  # must match pod/deployment labels
  ports:
    - port: 80        # service port (inside cluster)
      targetPort: 80  # container port
