apiVersion: v1
kind: Pod
metadata:
  name: portfolio-pod
  namespace: portfolio
spec:
  containers:
    - name: portfolio-container
      image: kapil-portfolio:latest
      imagePullPolicy: Never  # Important for local images
      ports:
        - containerPort: 80